#!/usr/bin/env bash
# Install offline voice dictation: venv + ~/.local/bin shims, systemd user unit,
# compositor keybind (Hyprland hold-to-talk, GNOME press-to-toggle), optional models.
# Safe to re-run for updates. Never commits anything. Model download is opt-in only.
set -euo pipefail

KEY="F9"
WITH_MODELS=0
CLEAN_MODELS=0

usage() {
    echo "Usage: install.sh [--key KEY] [--with-models] [--clean-models]"
    echo "  --key KEY       hold-to-talk key, default F9 (Hyprland) / toggle key (GNOME)"
    echo "  --with-models   download Moonshine-tiny q8 (~103 MB) + silero-vad (opt-in)"
    echo "  --clean-models  delete retired model files (Parakeet, base, SenseVoice,"
    echo "                  punct) from ~/.local/share/voxd/models, then exit"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --key) KEY="$2"; shift 2 ;;
        --with-models) WITH_MODELS=1; shift ;;
        --clean-models) CLEAN_MODELS=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown arg: $1"; usage; exit 1 ;;
    esac
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="$HOME/.local/share/voxd"
BIN_DIR="$HOME/.local/bin"
VENV="$PREFIX/venv"
# Retired model files from earlier stacks. Only these exact names are ever
# deleted; the current Moonshine-tiny dir and silero_vad.onnx are kept.
LEGACY_MODELS="parakeet.tar.bz2 parakeet-v3-int8 moonshine.tar.bz2 sensevoice.tar.bz2 punct.tar.bz2 sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8 sherpa-onnx-moonshine-base-en-int8 sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17 sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12"

clean_legacy_models() {
    echo "== clean retired models in $PREFIX/models =="
    FREED=0
    for name in $LEGACY_MODELS; do
        target="$PREFIX/models/$name"
        if [ -e "$target" ]; then
            size="$(du -sb "$target" | cut -f1)"
            FREED=$((FREED + size))
            echo "removing $name ($(numfmt --to=iec "$size"))"
            rm -rf "$target"
        fi
    done
    echo "reclaimed $(numfmt --to=iec "$FREED")"
}

if [ "$CLEAN_MODELS" -eq 1 ]; then
    clean_legacy_models
    exit 0
fi
MODEL_DIR="$PREFIX/models/moonshine-tiny-en-int8"
MODEL_URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-moonshine-tiny-en-int8.tar.bz2"
# Inner dir name inside MODEL_URL's tarball (upstream-controlled; update together).
MODEL_SRC_DIR="sherpa-onnx-moonshine-tiny-en-int8"
VAD_URL="https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1 ($2)"; exit 1; }; }
need systemctl "systemd user services required"
if ! command -v wtype >/dev/null 2>&1 && ! { command -v wl-copy >/dev/null 2>&1 && command -v hyprctl >/dev/null 2>&1; }; then
    echo "missing: need wtype, or wl-copy+hyprctl, for text insertion"; exit 1
fi
if command -v uv >/dev/null 2>&1; then HAVE_UV=1;
elif command -v python3 >/dev/null 2>&1; then HAVE_UV=0;
else echo "missing: need uv or python3 (>=3.12)"; exit 1; fi

echo "== venv =="
if [ ! -x "$VENV/bin/python" ]; then
    if [ "$HAVE_UV" -eq 1 ]; then uv venv --python 3.12 "$VENV"; else python3 -m venv "$VENV"; fi
fi
if [ "$HAVE_UV" -eq 1 ]; then uv pip install --python "$VENV/bin/python" "$REPO_DIR";
else "$VENV/bin/pip" install "$REPO_DIR"; fi

echo "== shims =="
mkdir -p "$BIN_DIR"
ln -sf "$VENV/bin/vox" "$BIN_DIR/vox"
ln -sf "$VENV/bin/voxd" "$BIN_DIR/voxd"
export PATH="$BIN_DIR:$PATH"

if [ "$WITH_MODELS" -eq 1 ]; then
    echo "== models (~110 MB, official sherpa-onnx releases) =="
    mkdir -p "$PREFIX/models"
    # A reinstall over an older stack must not leave retired models behind.
    clean_legacy_models
    if [ ! -f "$MODEL_DIR/encode.int8.onnx" ]; then
        curl -fSL -o "$PREFIX/moonshine.tar.bz2" "$MODEL_URL"
        tar -xf "$PREFIX/moonshine.tar.bz2" -C "$PREFIX/models"
        rm "$PREFIX/moonshine.tar.bz2"
        # Integrity: extraction must yield every file the worker loads.
        for f in preprocess.onnx encode.int8.onnx uncached_decode.int8.onnx cached_decode.int8.onnx tokens.txt; do
            [ -f "$PREFIX/models/$MODEL_SRC_DIR/$f" ] || { echo "missing model file: $f"; exit 1; }
        done
        # MODEL_DIR may hold a partial tree from an interrupted run; clear it so
        # mv renames (GNU mv would otherwise nest the tree inside the dir).
        rm -rf "$MODEL_DIR"
        mv "$PREFIX/models/$MODEL_SRC_DIR" "$MODEL_DIR"
    fi
    [ -f "$PREFIX/models/silero_vad.onnx" ] || curl -fSL -o "$PREFIX/models/silero_vad.onnx" "$VAD_URL"
    mkdir -p "$HOME/.config/voxd"
    cat > "$HOME/.config/voxd/config.toml" <<EOF
# Generated by install.sh. Absolute paths so the service works anywhere.
model_dir = "$MODEL_DIR"
vad_model = "$PREFIX/models/silero_vad.onnx"
worker_idle_timeout = 25
EOF
else
    echo "(skipping model download; re-run with --with-models, or set model_dir in ~/.config/voxd/config.toml)"
fi

echo "== service =="
mkdir -p "$HOME/.config/systemd/user"
sed "s|ExecStart=.*|ExecStart=$BIN_DIR/voxd|" "$REPO_DIR/systemd/voxd.service" > "$HOME/.config/systemd/user/voxd.service"
systemctl --user daemon-reload
# Restart (not enable --now, which is a no-op on an already-active service and
# would leave the previous build running).
systemctl --user enable voxd.service
systemctl --user restart voxd.service
# The service binds its socket asynchronously; wait for it before checking status.
SOCK="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/voxd.sock"
for _ in $(seq 1 100); do
    [ -S "$SOCK" ] && break
    sleep 0.2
done
[ -S "$SOCK" ] || { echo "voxd socket never appeared; see journalctl --user -u voxd.service"; exit 1; }
"$BIN_DIR/vox" status

echo "== keybind =="
VOX="$BIN_DIR/vox"
HAVE_HYPRLAND=0
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
    HAVE_HYPRLAND=1
    if [ -f "$HOME/.config/hypr/hyprland.conf" ]; then
        # Legacy config: managed snippet + source line (idempotent).
        cat > "$HOME/.config/voxd/hypr-binds.conf" <<EOF
# Generated by voxd install.sh. Do not edit; re-run install.sh to change the key.
bind = , $KEY, exec, $VOX start
bindr = , $KEY, exec, $VOX stop
EOF
        grep -q "voxd/hypr-binds.conf" "$HOME/.config/hypr/hyprland.conf" || \
            echo "source = $HOME/.config/voxd/hypr-binds.conf" >> "$HOME/.config/hypr/hyprland.conf"
        hyprctl reload
        echo "Hyprland hold-to-talk on $KEY installed (legacy config, reloaded)."
    else
        # Lua / non-legacy config: hyprctl keyword cannot edit it, so print the lines.
        echo "Hyprland uses a non-legacy (e.g. Lua) config; add these lines manually:"
        echo "  hl.bind(\"$KEY\", hl.dsp.exec_cmd(\"$VOX start\"))"
        echo "  hl.bind(\"$KEY\", hl.dsp.exec_cmd(\"$VOX stop\"), { release = true })"
    fi
elif [ "${XDG_CURRENT_DESKTOP:-}" = "GNOME" ] && command -v gsettings >/dev/null 2>&1; then
    # GNOME shortcuts fire on press only (no release event): toggle mode.
    SCHEMA="org.gnome.settings-daemon.plugins.media-keys"
    if gsettings list-schemas 2>/dev/null | grep -q "^$SCHEMA\$" && \
       gsettings list-keys "$SCHEMA" 2>/dev/null | grep -q custom-keybindings; then
        BINDING="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/voxd/"
        CUR="$(gsettings get "$SCHEMA" custom-keybindings)"
        if [ "$CUR" = "@as []" ]; then NEW="['$BINDING']";
        elif echo "$CUR" | grep -q voxd; then NEW="$CUR";
        else NEW="$(echo "$CUR" | sed "s/]$/, '$BINDING']/")"; fi
        gsettings set "$SCHEMA" custom-keybindings "$NEW"
        gsettings set "$SCHEMA.custom-keybinding:$BINDING" name "Voice dictation (toggle)"
        gsettings set "$SCHEMA.custom-keybinding:$BINDING" command "$VOX toggle"
        gsettings set "$SCHEMA.custom-keybinding:$BINDING" binding "$KEY"
        echo "GNOME toggle shortcut on $KEY installed (press to start, press again to stop)."
        echo "NOTE: GNOME has no key-release bindings; hold-to-talk is Hyprland-only."
    else
        echo "GNOME schema not as expected; set a custom shortcut to '$VOX toggle' manually."
    fi
else
    echo "Compositor '${XDG_CURRENT_DESKTOP:-unknown}' not handled automatically."
    echo "Hyprland: bind press/release to '$VOX start' / '$VOX stop'."
    echo "Others without release events: bind one shortcut to '$VOX toggle'."
fi

echo "== pill =="
if [ "$HAVE_HYPRLAND" -eq 1 ]; then
    if python3 -c "import gi; gi.require_version('Gtk', '4.0'); gi.require_version('Gtk4LayerShell', '1.0')" 2>/dev/null; then
        SITE="$("$VENV/bin/python" -c "import sysconfig; print(sysconfig.get_path('purelib'))")"
        cat > "$BIN_DIR/voxd-pill" <<EOF
#!/bin/sh
# Generated by voxd install.sh. Runs the pill on system Python with the
# venv's dictation package (pill_state only; no heavy imports).
# LD_PRELOAD works around gtk4-layer-shell's link order (else the window is
# not a layer surface and renders as a normal window).
for _lib in /usr/lib/libgtk4-layer-shell.so /usr/lib/liblayer-shell-preload.so; do
    [ -f "\$_lib" ] && export LD_PRELOAD="\$_lib" && break
done
PYTHONPATH="$SITE" exec /usr/bin/python3 "$PREFIX/pill.py" "\$@"
EOF
        chmod +x "$BIN_DIR/voxd-pill"
        cp "$REPO_DIR/ui/pill.py" "$PREFIX/pill.py"
        cp "$REPO_DIR/systemd/voxd-pill.service" "$HOME/.config/systemd/user/voxd-pill.service"
        systemctl --user daemon-reload
        systemctl --user enable --now voxd-pill.service
        echo "Listening pill installed (Hyprland overlay, follows vox start/stop)."
    else
        echo "pill skipped: need python3-gi + gtk4 + gtk-layer-shell (e.g. pacman -S python-gobject gtk4 gtk-layer-shell)"
    fi
else
    echo "(pill is Hyprland-only; skipping)"
fi

cat <<EOF
== done ==
Verify: focus a text editor, hold $KEY, speak, release. First run loads the
model (~1 s); the worker exits after 25 s idle and memory drops back.
Service logs: journalctl --user -u voxd.service
EOF
